#!/bin/bash
########################################################################
#                                                                      #
# temper_ temperature plugin for munin.                                #
# Part of "pcsensor-temper" package.                                   #
#                                                                      #
########################################################################
#                                                                      #
# Example plugin config:                                               #
#                                                                      #
#   [temper_*]                                                         #
#     env.HOSTNAME    <...>                                            #
#     env.LOCATION    <...>                                            #
#     env.CALIBRATION <INT>                                            #
#     env.UNIT        <C/F>                                            #
#                                                                      #
########################################################################

#set -euf -o pipefail

HOSTNAME=${HOSTNAME:-}
LOCATION=${LOCATION:-}
CALIBRATION=${CALIBRATION:-0}
UNIT=${UNIT:-}; UNIT=${UNIT^^}

basename=`basename "$0"`
file=`basename "$(readlink -f "$0")"`
c="${#file}"; DEVICE="${basename:c}"
mode=${1:-}; unset basename file c

# . $MUNIN_LIBDIR/plugins/plugin.sh
if [[ "$UNIT" != "F" ]]; then UNIT=C; fi
if [[ "$DEVICE" == "" ]]; then DEVICE=0; fi

if [ "$mode" = "autoconf" ]
then
	echo "no"
	exit
elif [[ "$mode" = "config" ]]
then
	if [[ "$HOSTNAME" != "" ]]
	then
		echo "host_name $HOSTNAME"
	fi

	if [[ "$UNIT" == "F" ]]
	then
		echo "temp.cdef temp,1.8,*,32,+"
		unitname="Fahrenheit"
	else
		unitname="Celsius"
	fi

	if [[ "$LOCATION" != "" ]]
	then
		echo "graph_title Humidity and Temperature in ${LOCATION}"
		echo "graph_info This graph shows the temperature and humidity for location ${LOCATION} in degree ${unitname}."
	else
		echo "graph_title Humidity and Temperature"
		echo "graph_info This graph shows the temperature and humidity in degree ${unitname}."
	fi

	#echo "graph_vlabel $UNIT" # <-- no °
	echo "graph_vlabel degree $unitname"

	echo "graph_category sensors"
	echo "temp.label Temperature"
	echo "hum.label Humidity"

	if [[ "$CALIBRATION" != "0" ]]
	then
		echo "temp.info current calibration: $CALIBRATION"
	fi

	exit
fi

OUT=/tmp/temper.py.out
python3 /usr/share/munin/plugins/temper.py > $OUT
# example: Bus 001 Dev 005 1a86:e025 TEMPerHUM_V3.8 26.60C 79.88F 49% - - -

echo -n 'temp.value ' # todo: error handling?
cat $OUT | awk '{print $7}' | sed 's/C$//'

echo -n 'hum.value ' # todo: error handling?
cat $OUT | awk '{print $9}' | sed 's/%$//'
